const pool = require('../db/db');
const generateSQL = require('../utils/gemini');
const { schemaCache, insightCache } = require('../utils/cache');
const crypto = require('crypto');

const handleQuery = async (req, res) => {
    const { prompt, datasetId, history } = req.body;
    const userId = req.user ? req.user.id : null;

    if (!prompt) {
        return res.status(400).json({ error: 'Please provide a prompt.' });
    }

    try {
        let tableName = 'videos';
        let columnsInfo = [];

        if (datasetId) {
            // Check schema cache first
            const cacheKey = `schema_${userId}_${datasetId}`;
            const cachedSchema = schemaCache.get(cacheKey);
            
            if (cachedSchema) {
                tableName = cachedSchema.tableName;
                columnsInfo = cachedSchema.columnsInfo;
            } else {
               const datasetRes = await pool.query(
  'SELECT table_name, columns FROM datasets WHERE id = $1 AND user_id = $2',
  [datasetId, userId]
);

if (datasetRes.rowCount === 0) {
  return res.status(403).json({ error: "Dataset not found or unauthorized" });
}
                tableName = datasetRes.rows[0].table_name;
                columnsInfo = datasetRes.rows[0].columns;
                // Store in cache
                schemaCache.set(cacheKey, { tableName, columnsInfo });
            }
        }

        // 1. Check Insight Cache for repeat questions
        const historyHash = history ? crypto.createHash('md5').update(JSON.stringify(history.slice(-3))).digest('hex') : 'no_hist';
        const insightKey = `insight_${userId}_${datasetId || 'default'}_${prompt}_${historyHash}`;
        let aiResponse = insightCache.get(insightKey);

        if (!aiResponse) {
            aiResponse = await generateSQL(prompt, tableName, columnsInfo, history);
            if (!aiResponse.error) {
                insightCache.set(insightKey, aiResponse);
            }
        }

        // 2. Handle AI Hallucinations/Out-of-Scope questions
        if (aiResponse.error) {
            return res.json({ error: aiResponse.error });
        }

        // 3. Handle General Conversation
        if (aiResponse.is_data_query === false) {
             let userMsgId = null, aiMsgId = null;
             if (datasetId && userId) {
                 const uRes = await pool.query(
                     'INSERT INTO chat_histories (user_id, dataset_id, role, text) VALUES ($1, $2, $3, $4) RETURNING id',
                     [userId, datasetId, 'user', prompt]
                 );
                 userMsgId = uRes.rows[0].id;
                 const aRes = await pool.query(
                     'INSERT INTO chat_histories (user_id, dataset_id, role, text, data) VALUES ($1, $2, $3, $4, $5) RETURNING id',
                     [userId, datasetId, 'ai', aiResponse.explanation, JSON.stringify({ suggested_follow_ups: aiResponse.suggested_follow_ups || [] })]
                 );
                 aiMsgId = aRes.rows[0].id;
             }

             return res.json({
                 datasetId,
                 prompt,
                 userMessageId: userMsgId,
                 aiMessageId: aiMsgId,
                 data_query: false,
                 explanation: aiResponse.explanation,
                 // Safety empty array for text chats
                 suggested_follow_ups: aiResponse.suggested_follow_ups || [] 
             });
        }

        // 4. Execute the SQL query generated by AI
        let result;
        try {
            result = await pool.query(aiResponse.sql_query);
            // --- DIAGNOSTIC LOGS: Proof that it works ---
            console.log("✅ Query executed successfully!");
            console.log("🧠 AI Response Object:", JSON.stringify(aiResponse, null, 2));
        } catch (sqlErr) {
            console.error("❌ SQL Execution Error:", sqlErr.message, "\nQuery:", aiResponse.sql_query);
            return res.json({ error: "AI generated an invalid SQL query. " + sqlErr.message });
        }

        // 5. Send the combined config and data to React
        
        let userMsgId = null, aiMsgId = null;
        if (datasetId && userId) {
             const uRes = await pool.query(
                 'INSERT INTO chat_histories (user_id, dataset_id, role, text) VALUES ($1, $2, $3, $4) RETURNING id',
                 [userId, datasetId, 'user', prompt]
             );
             userMsgId = uRes.rows[0].id;

             const aiFullData = {
                 chart_type: aiResponse.chart_type,
                 x_axis_column: aiResponse.x_axis_column,
                 y_axis_column: aiResponse.y_axis_column,
                 sql_used: aiResponse.sql_query,
                 data: result.rows,
                 suggested_follow_ups: aiResponse.suggested_follow_ups || []
             };

             const aRes = await pool.query(
                 'INSERT INTO chat_histories (user_id, dataset_id, role, text, data) VALUES ($1, $2, $3, $4, $5) RETURNING id',
                 [userId, datasetId, 'ai', aiResponse.explanation, JSON.stringify(aiFullData)]
             );
             aiMsgId = aRes.rows[0].id;
        }

        res.json({
            datasetId,
            prompt,
            userMessageId: userMsgId,
            aiMessageId: aiMsgId,
            data_query: true,
            chart_type: aiResponse.chart_type,
            x_axis_column: aiResponse.x_axis_column,
            y_axis_column: aiResponse.y_axis_column,
            explanation: aiResponse.explanation,
            sql_used: aiResponse.sql_query,
            data: result.rows,
            // Use the AI's questions, or an empty array if it generated none
            suggested_follow_ups: aiResponse.suggested_follow_ups || []
        });

    } catch (error) {
        console.error("Query Error:", error);
        res.status(500).json({ error: "Sorry, I couldn't generate a valid query for that." });
    }
};

module.exports = { handleQuery };
