const pool = require('../db/db');
const generateSQL = require('../utils/gemini');

const handleQuery = async (req, res) => {
    const { prompt, datasetId, history } = req.body;
    const userId = req.user ? req.user.id : null;

    if (!prompt) {
        return res.status(400).json({ error: 'Please provide a prompt.' });
    }

    try {
        let tableName = 'videos'; // default if no dataset provided
        let columnsInfo = [];

        if (datasetId) {
            // fetch dataset schema dynamically based on the dataset selected in frontend
            const datasetRes = await pool.query('SELECT table_name, columns FROM datasets WHERE id = $1', [datasetId]);
            if (datasetRes.rowCount === 0) {
                return res.status(404).json({ error: 'Dataset not found.' });
            }
            tableName = datasetRes.rows[0].table_name;
            columnsInfo = datasetRes.rows[0].columns;
        } else {
            // Hardcoded fallback schema
             columnsInfo = [
                { original: 'timestamp', name: 'timestamp', type: 'TIMESTAMP' },
                { original: 'video_id', name: 'video_id', type: 'TEXT' },
                { original: 'category', name: 'category', type: 'TEXT' },
                { original: 'language', name: 'language', type: 'TEXT' },
                { original: 'region', name: 'region', type: 'TEXT' },
                { original: 'duration_sec', name: 'duration_sec', type: 'BIGINT' },
                { original: 'views', name: 'views', type: 'BIGINT' },
                { original: 'likes', name: 'likes', type: 'BIGINT' },
                { original: 'comments', name: 'comments', type: 'BIGINT' },
                { original: 'shares', name: 'shares', type: 'BIGINT' },
                { original: 'sentiment_score', name: 'sentiment_score', type: 'DOUBLE PRECISION' },
                { original: 'ads_enabled', name: 'ads_enabled', type: 'BOOLEAN' },
             ];
        }

        // 1. Get the JSON object from Gemini
        const aiResponse = await generateSQL(prompt, tableName, columnsInfo, history);

        // 2. Handle AI Hallucinations/Out-of-Scope questions
        if (aiResponse.error) {
            return res.json({ error: aiResponse.error });
        }

        // 3. Handle General Conversation
        if (aiResponse.is_data_query === false) {
             let userMsgId = null, aiMsgId = null;
             if (datasetId && userId) {
                 const uRes = await pool.query(
                     'INSERT INTO chat_histories (user_id, dataset_id, role, text) VALUES ($1, $2, $3, $4) RETURNING id',
                     [userId, datasetId, 'user', prompt]
                 );
                 userMsgId = uRes.rows[0].id;
                 const aRes = await pool.query(
                     'INSERT INTO chat_histories (user_id, dataset_id, role, text, data) VALUES ($1, $2, $3, $4, $5) RETURNING id',
                     [userId, datasetId, 'ai', aiResponse.explanation, JSON.stringify({ suggested_follow_ups: aiResponse.suggested_follow_ups || [] })]
                 );
                 aiMsgId = aRes.rows[0].id;
             }

             return res.json({
                 datasetId,
                 prompt,
                 userMessageId: userMsgId,
                 aiMessageId: aiMsgId,
                 data_query: false,
                 explanation: aiResponse.explanation,
                 // Safety empty array for text chats
                 suggested_follow_ups: aiResponse.suggested_follow_ups || [] 
             });
        }

        // 4. Execute the SQL query generated by AI
        const result = await pool.query(aiResponse.sql_query);

        // --- DIAGNOSTIC LOGS: Proof that it works ---
        console.log("✅ Query executed successfully!");
        console.log("🧠 AI Response Object:", JSON.stringify(aiResponse, null, 2));

        // 5. Send the combined config and data to React
        
        let userMsgId = null, aiMsgId = null;
        if (datasetId && userId) {
             const uRes = await pool.query(
                 'INSERT INTO chat_histories (user_id, dataset_id, role, text) VALUES ($1, $2, $3, $4) RETURNING id',
                 [userId, datasetId, 'user', prompt]
             );
             userMsgId = uRes.rows[0].id;

             const aiFullData = {
                 chart_type: aiResponse.chart_type,
                 x_axis_column: aiResponse.x_axis_column,
                 y_axis_column: aiResponse.y_axis_column,
                 sql_used: aiResponse.sql_query,
                 data: result.rows,
                 suggested_follow_ups: aiResponse.suggested_follow_ups || []
             };

             const aRes = await pool.query(
                 'INSERT INTO chat_histories (user_id, dataset_id, role, text, data) VALUES ($1, $2, $3, $4, $5) RETURNING id',
                 [userId, datasetId, 'ai', aiResponse.explanation, JSON.stringify(aiFullData)]
             );
             aiMsgId = aRes.rows[0].id;
        }

        res.json({
            datasetId,
            prompt,
            userMessageId: userMsgId,
            aiMessageId: aiMsgId,
            data_query: true,
            chart_type: aiResponse.chart_type,
            x_axis_column: aiResponse.x_axis_column,
            y_axis_column: aiResponse.y_axis_column,
            explanation: aiResponse.explanation,
            sql_used: aiResponse.sql_query,
            data: result.rows,
            // Use the AI's questions, or an empty array if it generated none
            suggested_follow_ups: aiResponse.suggested_follow_ups || []
        });

    } catch (error) {
        console.error("Query Error:", error);
        res.status(500).json({ error: "Sorry, I couldn't generate a valid query for that." });
    }
};

module.exports = { handleQuery };
